"""update douban order

Revision ID: 105894cc3fae
Revises: 1981b2588261
Create Date: 2015-02-04 16:07:28.748221

"""

# revision identifiers, used by Alembic.
revision = '105894cc3fae'
down_revision = '1981b2588261'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_douban_order', sa.Column('medium_CPM', sa.Integer(), nullable=True))
    op.add_column('bra_douban_order', sa.Column('sale_CPM', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_douban_order', 'sale_CPM')
    op.drop_column('bra_douban_order', 'medium_CPM')
    ### end Alembic commands ###
