"""add colum contact in agent

Revision ID: 1064cb14cbf3
Revises: 2f6ba45519b0
Create Date: 2016-07-25 15:34:03.244679

"""

# revision identifiers, used by Alembic.
revision = '1064cb14cbf3'
down_revision = '2f6ba45519b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('contact', sa.String(length=50), nullable=True))
    op.add_column('agent', sa.Column('contact_phone', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'contact_phone')
    op.drop_column('agent', 'contact')
    ### end Alembic commands ###
