"""add colum status in frameword_order

Revision ID: 107e121a1249
Revises: 4038a43c89c
Create Date: 2015-03-30 18:05:29.854873

"""

# revision identifiers, used by Alembic.
revision = '107e121a1249'
down_revision = '4038a43c89c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_framework_order', sa.Column('status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_framework_order', 'status')
    ### end Alembic commands ###
