"""add recuited date

Revision ID: 1154c54dd33b
Revises: 31661e578296
Create Date: 2015-08-14 17:35:21.484468

"""

# revision identifiers, used by Alembic.
revision = '1154c54dd33b'
down_revision = '31661e578296'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('recruited_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'recruited_date')
    ### end Alembic commands ###
