"""add table personal outsource

Revision ID: 119bb1687ffa
Revises: 50ad8e409732
Create Date: 2015-09-14 16:19:51.544036

"""

# revision identifiers, used by Alembic.
revision = '119bb1687ffa'
down_revision = '50ad8e409732'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merget_client_personal_outsources',
    sa.Column('mergerpersonalouttsource_id', sa.Integer(), nullable=True),
    sa.Column('doubanoutsource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doubanoutsource_id'], ['out_source.id'], ),
    sa.ForeignKeyConstraint(['mergerpersonalouttsource_id'], ['merger_personal_out_source.id'], )
    )
    op.create_table('merget_douban_personal_outsources',
    sa.Column('mergerdoubanoupersonaltsource_id', sa.Integer(), nullable=True),
    sa.Column('doubanoutsource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doubanoutsource_id'], ['douban_out_source.id'], ),
    sa.ForeignKeyConstraint(['mergerdoubanoupersonaltsource_id'], ['merger_douban_personal_out_source.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merget_douban_personal_outsources')
    op.drop_table('merget_client_personal_outsources')
    ### end Alembic commands ###
