"""add invoice table

Revision ID: 12b8c33ce34a
Revises: 2031f01d6195
Create Date: 2015-03-18 17:02:52.154435

"""

# revision identifiers, used by Alembic.
revision = '12b8c33ce34a'
down_revision = '2031f01d6195'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
