"""add colum type in onduty

Revision ID: 12c0a209e51a
Revises: 53b27f3f5952
Create Date: 2016-01-13 14:42:41.334195

"""

# revision identifiers, used by Alembic.
revision = '12c0a209e51a'
down_revision = '53b27f3f5952'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_onduty', sa.Column('type', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_onduty', 'type')
    ### end Alembic commands ###
