"""add column is_delete for table 'searchad_bra_client_order_bill' 

Revision ID: 136dd738c2dd
Revises: d5ab4da2fcb
Create Date: 2016-09-19 16:19:35.206773

"""

# revision identifiers, used by Alembic.
revision = '136dd738c2dd'
down_revision = 'd5ab4da2fcb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('searchad_bra_client_order_bill', sa.Column('is_delete', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('searchad_bra_client_order_bill', 'is_delete')
    ### end Alembic commands ###
