"""update cost_table

Revision ID: 1618d7630814
Revises: 22de9d2b21
Create Date: 2016-06-06 18:20:00.761231

"""

# revision identifiers, used by Alembic.
revision = '1618d7630814'
down_revision = '22de9d2b21'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_client_order_other_cost', sa.Column('company', sa.String(length=100), nullable=True))
    op.add_column('bra_douban_order_other_cost', sa.Column('company', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_douban_order_other_cost', 'company')
    op.drop_column('bra_client_order_other_cost', 'company')
    ### end Alembic commands ###
