"""add colum finish_time in search order

Revision ID: 161ced3bbd8a
Revises: 403f1953348b
Create Date: 2015-12-10 17:40:50.789877

"""

# revision identifiers, used by Alembic.
revision = '161ced3bbd8a'
down_revision = '403f1953348b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_searchAd_framework_order', sa.Column('finish_time', sa.DateTime(), nullable=True))
    op.add_column('searchAd_bra_client_order', sa.Column('finish_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('searchAd_bra_client_order', 'finish_time')
    op.drop_column('bra_searchAd_framework_order', 'finish_time')
    ### end Alembic commands ###
