"""add table medium frameworkorder

Revision ID: 17f176b26fd8
Revises: 4b20f61b4f72
Create Date: 2016-01-21 12:39:05.478817

"""

# revision identifiers, used by Alembic.
revision = '17f176b26fd8'
down_revision = '4b20f61b4f72'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bra_medium_framework_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('contract', sa.String(length=100), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('contract_type', sa.Integer(), nullable=True),
    sa.Column('client_start', sa.Date(), nullable=True),
    sa.Column('client_end', sa.Date(), nullable=True),
    sa.Column('contract_status', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('finish_time', sa.DateTime(), nullable=True),
    sa.Column('inad_rebate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medium_framework_order_medium_users',
    sa.Column('media_user_id', sa.Integer(), nullable=True),
    sa.Column('medium_framework_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['medium_framework_order_id'], ['bra_medium_framework_order.id'], )
    )
    op.create_table('medium_framework_order_mediums',
    sa.Column('medium_id', sa.Integer(), nullable=True),
    sa.Column('medium_framework_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medium_framework_order_id'], ['bra_medium_framework_order.id'], ),
    sa.ForeignKeyConstraint(['medium_id'], ['medium.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medium_framework_order_mediums')
    op.drop_table('medium_framework_order_medium_users')
    op.drop_table('bra_medium_framework_order')
    ### end Alembic commands ###
