"""rm client agent

Revision ID: 190bb0293563
Revises: cac45bb56be
Create Date: 2014-12-15 17:00:34.739539

"""

# revision identifiers, used by Alembic.
revision = '190bb0293563'
down_revision = 'cac45bb56be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_order', 'agent_id')
    op.drop_column('bra_order', 'client_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_order', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bra_order', sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
