"""add colum status on user_leave

Revision ID: 194af7c724af
Revises: 421199db1d88
Create Date: 2015-04-24 12:01:35.681403

"""

# revision identifiers, used by Alembic.
revision = '194af7c724af'
down_revision = '421199db1d88'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_leave', sa.Column('status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_leave', 'status')
    ### end Alembic commands ###
