"""add cpm to order

Revision ID: 1981b2588261
Revises: 37d04625d281
Create Date: 2015-02-03 17:50:21.062089

"""

# revision identifiers, used by Alembic.
revision = '1981b2588261'
down_revision = '37d04625d281'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('out_source')
    op.add_column('bra_order', sa.Column('medium_CPM', sa.Integer(), nullable=True))
    op.add_column('bra_order', sa.Column('sale_CPM', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_order', 'sale_CPM')
    op.drop_column('bra_order', 'medium_CPM')
    op.create_table('out_source',
    sa.Column('id', sa.INTEGER(), server_default="nextval('out_source_id_seq'::regclass)", nullable=False),
    sa.Column('num', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'out_source_pkey')
    )
    ### end Alembic commands ###
