"""add douban order

Revision ID: 19d99d807b2b
Revises: 4d534110cc55
Create Date: 2015-01-07 15:12:51.685711

"""

# revision identifiers, used by Alembic.
revision = '19d99d807b2b'
down_revision = '4d534110cc55'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bra_douban_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('contract', sa.String(length=100), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.Column('contract_type', sa.Integer(), nullable=True),
    sa.Column('client_start', sa.Date(), nullable=True),
    sa.Column('client_end', sa.Date(), nullable=True),
    sa.Column('reminde_date', sa.Date(), nullable=True),
    sa.Column('contract_status', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('douban_order_direct_sales',
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('douban_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['douban_order_id'], ['bra_douban_order.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['user.id'], )
    )
    op.create_table('douban_order_agent_sales',
    sa.Column('agent_sale_id', sa.Integer(), nullable=True),
    sa.Column('douban_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_sale_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['douban_order_id'], ['bra_douban_order.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('douban_order_agent_sales')
    op.drop_table('douban_order_direct_sales')
    op.drop_table('bra_douban_order')
    ### end Alembic commands ###
