"""add table searchAd_framework_order

Revision ID: 1a7a0381a06b
Revises: 7c2553bead
Create Date: 2015-08-28 12:14:21.345298

"""

# revision identifiers, used by Alembic.
revision = '1a7a0381a06b'
down_revision = '7c2553bead'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bra_searchAd_framework_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('contract', sa.String(length=100), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.Column('contract_type', sa.Integer(), nullable=True),
    sa.Column('client_start', sa.Date(), nullable=True),
    sa.Column('client_end', sa.Date(), nullable=True),
    sa.Column('reminde_date', sa.Date(), nullable=True),
    sa.Column('contract_status', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('rebate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['searchAd_agent.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('framework_order_searchAd_sales',
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('framework_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['framework_order_id'], ['bra_searchAd_framework_order.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('framework_order_searchAd_sales')
    op.drop_table('bra_searchAd_framework_order')
    ### end Alembic commands ###
