"""add colum self_agent_rebate in searchad_client_order

Revision ID: 1ac203a35b62
Revises: 1618d7630814
Create Date: 2016-06-28 16:04:46.488339

"""

# revision identifiers, used by Alembic.
revision = '1ac203a35b62'
down_revision = '1618d7630814'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('searchAd_bra_client_order', sa.Column('self_agent_rebate', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('searchAd_bra_client_order', 'self_agent_rebate')
    ### end Alembic commands ###
