"""add table merger_douban_out_source

Revision ID: 1aeab9b2d6a2
Revises: f1febdac97
Create Date: 2015-04-22 13:50:16.207149

"""

# revision identifiers, used by Alembic.
revision = '1aeab9b2d6a2'
down_revision = 'f1febdac97'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merger_douban_out_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('invoice', sa.Boolean(), nullable=True),
    sa.Column('pay_num', sa.Float(), nullable=True),
    sa.Column('num', sa.Float(), nullable=True),
    sa.Column('remark', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['out_source_target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merget_douban_outsources',
    sa.Column('mergerdoubanoutsource_id', sa.Integer(), nullable=True),
    sa.Column('doubanoutsource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doubanoutsource_id'], ['douban_out_source.id'], ),
    sa.ForeignKeyConstraint(['mergerdoubanoutsource_id'], ['merger_douban_out_source.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merget_douban_outsources')
    op.drop_table('merger_douban_out_source')
    ### end Alembic commands ###
