"""add colum subject in client_order and edit_client_order

Revision ID: 1afeb6f303df
Revises: 4d8394f3941
Create Date: 2016-08-22 10:50:09.295927

"""

# revision identifiers, used by Alembic.
revision = '1afeb6f303df'
down_revision = '4d8394f3941'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_client_order', sa.Column('subject', sa.Integer(), nullable=True))
    op.add_column('bra_edit_client_order', sa.Column('subject', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_edit_client_order', 'subject')
    op.drop_column('bra_client_order', 'subject')
    ### end Alembic commands ###
