"""update douban order

Revision ID: 1c482661b4b1
Revises: 19d99d807b2b
Create Date: 2015-01-07 15:59:39.019391

"""

# revision identifiers, used by Alembic.
revision = '1c482661b4b1'
down_revision = '19d99d807b2b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_douban_order', sa.Column('campaign', sa.String(length=100), nullable=True))
    op.add_column('douban_order_direct_sales', sa.Column('direct_sale_id', sa.Integer(), nullable=True))
    op.drop_column('douban_order_direct_sales', 'sale_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('douban_order_direct_sales', sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('douban_order_direct_sales', 'direct_sale_id')
    op.drop_column('bra_douban_order', 'campaign')
    ### end Alembic commands ###
