"""add invoice to table searchad_bra_client_order_bill

Revision ID: 1ca90d044092
Revises: 3accc50b76
Create Date: 2016-09-06 16:30:52.332980

"""

# revision identifiers, used by Alembic.
revision = '1ca90d044092'
down_revision = '3accc50b76'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.add_column('searchad_bra_client_order_bill', sa.Column('invoice_apply_sum', sa.Float(), nullable=True))
    op.add_column('searchad_bra_client_order_bill', sa.Column('invoice_pass_sum', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('searchad_bra_client_order_bill', 'invoice_pass_sum')
    op.drop_column('searchad_bra_client_order_bill', 'invoice_apply_sum')
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    ### end Alembic commands ###
