"""add colum creator in bra_medium_rebate

Revision ID: 1e4d9ed8d5db
Revises: 3ed998b96ab8
Create Date: 2015-06-29 12:41:35.394913

"""

# revision identifiers, used by Alembic.
revision = '1e4d9ed8d5db'
down_revision = '3ed998b96ab8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_medium_rebate', sa.Column('creator_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_medium_rebate', 'creator_id')
    ### end Alembic commands ###
