"""add medium money

Revision ID: 1e5ec46c547b
Revises: 21aa9110d708
Create Date: 2015-02-10 18:32:01.808688

"""

# revision identifiers, used by Alembic.
revision = '1e5ec46c547b'
down_revision = '21aa9110d708'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_order', sa.Column('medium_money2', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_order', 'medium_money2')
    ### end Alembic commands ###
