"""add colum medium_group in client_order

Revision ID: 1e75cd1c8b34
Revises: 42aafca548a3
Create Date: 2016-08-01 11:38:49.552686

"""

# revision identifiers, used by Alembic.
revision = '1e75cd1c8b34'
down_revision = '42aafca548a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_intention_order', sa.Column('medium_group_id', sa.Integer(), nullable=True))
    op.add_column('bra_order', sa.Column('medium_group_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_order', 'medium_group_id')
    op.drop_column('bra_intention_order', 'medium_group_id')
    ### end Alembic commands ###
