"""add table completion

Revision ID: 1ee54c609d14
Revises: 3b31071e1f4d
Create Date: 2016-04-11 15:37:21.385002

"""

# revision identifiers, used by Alembic.
revision = '1ee54c609d14'
down_revision = '3b31071e1f4d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(length=7), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'rate', name='_completion_user_rate')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('completion')
    ### end Alembic commands ###
