"""add table CompletionIncrement

Revision ID: 1f6e397add11
Revises: 1afeb6f303df
Create Date: 2016-08-22 15:46:01.143027

"""

# revision identifiers, used by Alembic.
revision = '1f6e397add11'
down_revision = '1afeb6f303df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completion_increment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(length=7), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('completion_increment')
    ### end Alembic commands ###
