"""add column invoice_num in invoice

Revision ID: 1fbb54143a8e
Revises: 38420eddd91c
Create Date: 2015-03-25 18:38:10.918673

"""

# revision identifiers, used by Alembic.
revision = '1fbb54143a8e'
down_revision = '38420eddd91c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_invoice', sa.Column('invoice_num', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_invoice', 'invoice_num')
    ### end Alembic commands ###
