"""add framework order

Revision ID: 1fd3e0a5fd14
Revises: 9791f847e
Create Date: 2014-12-30 16:50:15.940968

"""

# revision identifiers, used by Alembic.
revision = '1fd3e0a5fd14'
down_revision = '9791f847e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bra_framework_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('contract', sa.String(length=100), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.Column('contract_type', sa.Integer(), nullable=True),
    sa.Column('client_start', sa.Date(), nullable=True),
    sa.Column('client_end', sa.Date(), nullable=True),
    sa.Column('reminde_date', sa.Date(), nullable=True),
    sa.Column('contract_status', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['bra_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('framework_order_direct_sales',
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], ['bra_framework_order.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['user.id'], )
    )
    op.create_table('framework_order_agent_sales',
    sa.Column('agent_sale_id', sa.Integer(), nullable=True),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_sale_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['client_order_id'], ['bra_framework_order.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('framework_order_agent_sales')
    op.drop_table('framework_order_direct_sales')
    op.drop_table('bra_framework_order')
    ### end Alembic commands ###
