"""add tax info on agent

Revision ID: 2031f01d6195
Revises: 2bf047e8c1b8
Create Date: 2015-03-18 15:09:24.999209

"""

# revision identifiers, used by Alembic.
revision = '2031f01d6195'
down_revision = '2bf047e8c1b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('address', sa.String(length=100), nullable=True))
    op.add_column('agent', sa.Column('bank', sa.String(length=100), nullable=True))
    op.add_column('agent', sa.Column('bank_num', sa.String(length=100), nullable=True))
    op.add_column('agent', sa.Column('phone_num', sa.String(length=100), nullable=True))
    op.add_column('agent', sa.Column('tax_num', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'tax_num')
    op.drop_column('agent', 'phone_num')
    op.drop_column('agent', 'bank_num')
    op.drop_column('agent', 'bank')
    op.drop_column('agent', 'address')
    ### end Alembic commands ###
