"""add attachment type

Revision ID: 20756762ccf1
Revises: 2a9e590cadee
Create Date: 2014-12-16 16:32:39.351099

"""

# revision identifiers, used by Alembic.
revision = '20756762ccf1'
down_revision = '2a9e590cadee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_attachment', sa.Column('attachment_type', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_attachment', 'attachment_type')
    ### end Alembic commands ###
