"""add colum in agent_medium_rebate

Revision ID: 219246606072
Revises: 6209c388432
Create Date: 2016-07-28 13:48:32.539491

"""

# revision identifiers, used by Alembic.
revision = '219246606072'
down_revision = '6209c388432'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_agent_medium_rebate', sa.Column('medium_name', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_agent_medium_rebate', 'medium_name')
    ### end Alembic commands ###
