"""add outsource

Revision ID: 21aa9110d708
Revises: 105894cc3fae
Create Date: 2015-02-06 18:21:26.702144

"""

# revision identifiers, used by Alembic.
revision = '21aa9110d708'
down_revision = '105894cc3fae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('out_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('medium_order_id', sa.Integer(), nullable=True),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('subtype', sa.Integer(), nullable=True),
    sa.Column('invoice', sa.Boolean(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('remark', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medium_order_id'], ['bra_order.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['out_source_target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('out_source')
    ### end Alembic commands ###
