"""add table media medium_group_media_rebate

Revision ID: 21b448cb6a09
Revises: 5ab57895e7c2
Create Date: 2016-08-02 11:43:44.302550

"""

# revision identifiers, used by Alembic.
revision = '21b448cb6a09'
down_revision = '5ab57895e7c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bra_medium_group_media_rebate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medium_group_id', sa.Integer(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('rebate', sa.Float(), nullable=True),
    sa.Column('year', sa.Date(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['medium_group_id'], ['medium_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medium_group_id', 'media_id', 'year', name='_medium_group_media_year')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bra_medium_group_media_rebate')
    op.drop_table('media')
    ### end Alembic commands ###
