"""add table client_medium_order_invoice

Revision ID: 22de9d2b21
Revises: 558ceb2d5be8
Create Date: 2016-05-30 14:12:55.718206

"""

# revision identifiers, used by Alembic.
revision = '22de9d2b21'
down_revision = '558ceb2d5be8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bra_client_medium_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_medium_order_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('bank_id', sa.String(length=50), nullable=True),
    sa.Column('bank', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('invoice_type', sa.Integer(), nullable=True),
    sa.Column('invoice_status', sa.Integer(), nullable=True),
    sa.Column('invoice_num', sa.String(length=200), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('back_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_medium_order_id'], ['bra_client_medium_order.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bra_client_medium_invoice')
    ### end Alembic commands ###
