"""add column pwd table case

Revision ID: 2351dcdcf715
Revises: 161ced3bbd8a
Create Date: 2015-12-21 10:47:51.910211

"""

# revision identifiers, used by Alembic.
revision = '2351dcdcf715'
down_revision = '161ced3bbd8a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_case', sa.Column('pwd', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_case', 'pwd')
    ### end Alembic commands ###
