"""add c_score in user_okr

Revision ID: 24f0b264b5bd
Revises: 1046bd7a3ed1
Create Date: 2016-10-11 09:36:09.403580

"""

# revision identifiers, used by Alembic.
revision = '24f0b264b5bd'
down_revision = '1046bd7a3ed1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_okr', sa.Column('c_score', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_okr', 'c_score')
    ### end Alembic commands ###
