"""add campaign

Revision ID: 254667d5628a
Revises: 1a928bfcfa5f
Create Date: 2015-01-12 12:58:52.763770

"""

# revision identifiers, used by Alembic.
revision = '254667d5628a'
down_revision = '1a928bfcfa5f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_associated_douban_order', sa.Column('campaign', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_associated_douban_order', 'campaign')
    ### end Alembic commands ###
