"""add table rebate_order invoice

Revision ID: 25ded65f110d
Revises: 4154756e95ae
Create Date: 2015-11-18 17:07:17.881018

"""

# revision identifiers, used by Alembic.
revision = '25ded65f110d'
down_revision = '4154756e95ae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searchad_bra_rebate_agent_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rebate_order_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('bank_id', sa.String(length=100), nullable=True),
    sa.Column('bank', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('pay_money', sa.Float(), nullable=True),
    sa.Column('invoice_type', sa.Integer(), nullable=True),
    sa.Column('invoice_status', sa.Integer(), nullable=True),
    sa.Column('invoice_num', sa.String(length=200), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.Column('pay_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('bool_pay', sa.Boolean(), nullable=True),
    sa.Column('bool_invoice', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['searchAd_agent.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rebate_order_id'], ['searchad_bra_rebate_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchad_bra_rebate_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rebate_order_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('bank_id', sa.String(length=50), nullable=True),
    sa.Column('bank', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('invoice_type', sa.Integer(), nullable=True),
    sa.Column('invoice_status', sa.Integer(), nullable=True),
    sa.Column('invoice_num', sa.String(length=200), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('back_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rebate_order_id'], ['searchad_bra_rebate_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchad_bra_rebate_agent_invoice_pay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_invoice_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.Column('pay_status', sa.Integer(), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('pay_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_invoice_id'], ['searchad_bra_rebate_agent_invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('searchad_bra_rebate_agent_invoice_pay')
    op.drop_table('searchad_bra_rebate_invoice')
    op.drop_table('searchad_bra_rebate_agent_invoice')
    ### end Alembic commands ###
