"""add colum in framework_order

Revision ID: 272cc4af8f0b
Revises: 2a3a99449ad3
Create Date: 2015-07-06 16:54:05.742414

"""

# revision identifiers, used by Alembic.
revision = '272cc4af8f0b'
down_revision = '2a3a99449ad3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_framework_order', sa.Column('douban_contract', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_framework_order', 'douban_contract')
    ### end Alembic commands ###
