"""add table merger_out_source

Revision ID: 27a73dbf3b0b
Revises: 54df5ae8e5c2
Create Date: 2015-04-21 10:58:59.953215

"""

# revision identifiers, used by Alembic.
revision = '27a73dbf3b0b'
down_revision = '54df5ae8e5c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merger_out_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('invoice', sa.Boolean(), nullable=True),
    sa.Column('pay_num', sa.Float(), nullable=True),
    sa.Column('num', sa.Float(), nullable=True),
    sa.Column('remark', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['out_source_target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merget_outsources',
    sa.Column('mergeroutsource_id', sa.Integer(), nullable=True),
    sa.Column('outsource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mergeroutsource_id'], ['merger_out_source.id'], ),
    sa.ForeignKeyConstraint(['outsource_id'], ['out_source.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merget_outsources')
    op.drop_table('merger_out_source')
    ### end Alembic commands ###
