"""add table medium_back_money

Revision ID: 27bdd1d4ad8c
Revises: d0322c4ef81
Create Date: 2016-01-07 15:36:18.289237

"""

# revision identifiers, used by Alembic.
revision = '27bdd1d4ad8c'
down_revision = 'd0322c4ef81'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bra_client_order_medium_back_money',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('back_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], ['bra_client_order.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['bra_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bra_client_order_medium_back_money')
    ### end Alembic commands ###
