"""add table edit order

Revision ID: 28d5ea8eaef0
Revises: 36ec9d24c5c1
Create Date: 2016-08-11 10:44:06.684538

"""

# revision identifiers, used by Alembic.
revision = '28d5ea8eaef0'
down_revision = '36ec9d24c5c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bra_edit_client_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('campaign', sa.String(length=100), nullable=True),
    sa.Column('contract', sa.String(length=100), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('contract_type', sa.Integer(), nullable=True),
    sa.Column('client_start', sa.Date(), nullable=True),
    sa.Column('client_end', sa.Date(), nullable=True),
    sa.Column('reminde_date', sa.Date(), nullable=True),
    sa.Column('resource_type', sa.Integer(), nullable=True),
    sa.Column('sale_type', sa.Integer(), nullable=True),
    sa.Column('contract_status', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('finish_time', sa.DateTime(), nullable=True),
    sa.Column('self_agent_rebate', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['client_order_id'], ['bra_client_order.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bra_back_edit_client_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edit_client_order_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['edit_client_order_id'], ['bra_edit_client_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bra_edit_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('campaign', sa.String(length=100), nullable=True),
    sa.Column('medium_group_id', sa.Integer(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('medium_contract', sa.String(length=100), nullable=True),
    sa.Column('medium_money2', sa.Float(), nullable=True),
    sa.Column('sale_money', sa.Float(), nullable=True),
    sa.Column('medium_CPM', sa.Integer(), nullable=True),
    sa.Column('sale_CPM', sa.Integer(), nullable=True),
    sa.Column('medium_start', sa.Date(), nullable=True),
    sa.Column('medium_end', sa.Date(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('finish_time', sa.DateTime(), nullable=True),
    sa.Column('self_medium_rebate', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['medium_group_id'], ['medium_group.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['bra_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edit_client_order_replace_sales',
    sa.Column('replace_sale_id', sa.Integer(), nullable=True),
    sa.Column('edit_client_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edit_client_order_id'], ['bra_edit_client_order.id'], ),
    sa.ForeignKeyConstraint(['replace_sale_id'], ['user.id'], )
    )
    op.create_table('edit_client_order_assistant_sales',
    sa.Column('assistant_sale_id', sa.Integer(), nullable=True),
    sa.Column('edit_client_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assistant_sale_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['edit_client_order_id'], ['bra_edit_client_order.id'], )
    )
    op.create_table('edit_client_order_agent_sales',
    sa.Column('agent_sale_id', sa.Integer(), nullable=True),
    sa.Column('edit_client_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_sale_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['edit_client_order_id'], ['bra_edit_client_order.id'], )
    )
    op.create_table('edit_client_order_direct_sales',
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('edit_client_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edit_client_order_id'], ['bra_edit_client_order.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['user.id'], )
    )
    op.create_table('edit_client_order_medium_orders',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('edit_client_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edit_client_order_id'], ['bra_edit_client_order.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['bra_edit_order.id'], )
    )
    op.create_table('edit_order_users_operater',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('edit_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edit_order_id'], ['bra_edit_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('edit_order_users_designerer',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('edit_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edit_order_id'], ['bra_edit_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('edit_order_users_planer',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('edit_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edit_order_id'], ['bra_edit_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edit_order_users_planer')
    op.drop_table('edit_order_users_designerer')
    op.drop_table('edit_order_users_operater')
    op.drop_table('edit_client_order_medium_orders')
    op.drop_table('edit_client_order_direct_sales')
    op.drop_table('edit_client_order_agent_sales')
    op.drop_table('edit_client_order_assistant_sales')
    op.drop_table('edit_client_order_replace_sales')
    op.drop_table('bra_edit_order')
    op.drop_table('bra_back_edit_client_order')
    op.drop_table('bra_edit_client_order')
    ### end Alembic commands ###
