"""add colum self in kpi table

Revision ID: 29946b1da9ac
Revises: 32064b0b2eff
Create Date: 2015-07-21 17:35:21.522398

"""

# revision identifiers, used by Alembic.
revision = '29946b1da9ac'
down_revision = '32064b0b2eff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preformance_evaluation', sa.Column('self_KR_score', sa.Float(), nullable=True))
    op.add_column('user_preformance_evaluation', sa.Column('self_ability_score', sa.Float(), nullable=True))
    op.add_column('user_preformance_evaluation', sa.Column('self_manage_score', sa.Float(), nullable=True))
    op.add_column('user_preformance_evaluation', sa.Column('self_total_score', sa.Float(), nullable=True))
    op.add_column('user_preformance_evaluation', sa.Column('self_upper_score', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preformance_evaluation', 'self_upper_score')
    op.drop_column('user_preformance_evaluation', 'self_total_score')
    op.drop_column('user_preformance_evaluation', 'self_manage_score')
    op.drop_column('user_preformance_evaluation', 'self_ability_score')
    op.drop_column('user_preformance_evaluation', 'self_KR_score')
    ### end Alembic commands ###
