"""add table bref in planning

Revision ID: 29b6d6f2b33
Revises: e48d7e4a8ff
Create Date: 2015-10-22 16:45:07.416966

"""

# revision identifiers, used by Alembic.
revision = '29b6d6f2b33'
down_revision = 'e48d7e4a8ff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bra_planning_bref',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('agent', sa.String(length=200), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('product', sa.String(length=100), nullable=True),
    sa.Column('target', sa.String(length=200), nullable=True),
    sa.Column('background', sa.String(length=250), nullable=True),
    sa.Column('push_target', sa.String(length=250), nullable=True),
    sa.Column('push_theme', sa.String(length=250), nullable=True),
    sa.Column('push_time', sa.String(length=250), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('is_temp', sa.Integer(), nullable=True),
    sa.Column('agent_type', sa.Integer(), nullable=True),
    sa.Column('use_type', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('get_time', sa.DateTime(), nullable=True),
    sa.Column('intent_medium', sa.String(length=100), nullable=True),
    sa.Column('suggest', sa.String(length=200), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('follow_id', sa.Integer(), nullable=True),
    sa.Column('to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bra_planning_bref')
    ### end Alembic commands ###
