"""add colum rebate in frameworkorder

Revision ID: 2a3a99449ad3
Revises: 1e4d9ed8d5db
Create Date: 2015-06-30 11:51:33.287698

"""

# revision identifiers, used by Alembic.
revision = '2a3a99449ad3'
down_revision = '1e4d9ed8d5db'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_framework_order', sa.Column('douban_rebate', sa.Float(), nullable=True))
    op.add_column('bra_framework_order', sa.Column('inad_rebate', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_framework_order', 'inad_rebate')
    op.drop_column('bra_framework_order', 'douban_rebate')
    ### end Alembic commands ###
