"""add table bra_intention_order

Revision ID: 2a96699469d7
Revises: 59490ed174d0
Create Date: 2016-04-14 15:08:09.153816

"""

# revision identifiers, used by Alembic.
revision = '2a96699469d7'
down_revision = '59490ed174d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bra_intention_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=100), nullable=True),
    sa.Column('medium_id', sa.Integer(), nullable=True),
    sa.Column('complete_percent', sa.Integer(), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('client', sa.String(length=100), nullable=True),
    sa.Column('campaign', sa.String(length=100), nullable=True),
    sa.Column('client_start', sa.Date(), nullable=True),
    sa.Column('client_end', sa.Date(), nullable=True),
    sa.Column('client_start_year', sa.Integer(), nullable=True),
    sa.Column('client_end_year', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bra_intention_order_client_end_year'), 'bra_intention_order', ['client_end_year'], unique=False)
    op.create_index(op.f('ix_bra_intention_order_client_start_year'), 'bra_intention_order', ['client_start_year'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bra_intention_order_client_start_year'), table_name='bra_intention_order')
    op.drop_index(op.f('ix_bra_intention_order_client_end_year'), table_name='bra_intention_order')
    op.drop_table('bra_intention_order')
    ### end Alembic commands ###
