"""add attachment mixin

Revision ID: 2a9e590cadee
Revises: 229d167b0ad8
Create Date: 2014-12-16 15:17:31.984683

"""

# revision identifiers, used by Alembic.
revision = '2a9e590cadee'
down_revision = '229d167b0ad8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bra_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bra_attachment')
    ### end Alembic commands ###
