"""team add location

Revision ID: 2ac75a48af33
Revises: 475db38a4544
Create Date: 2015-01-14 11:05:43.367864

"""

# revision identifiers, used by Alembic.
revision = '2ac75a48af33'
down_revision = '475db38a4544'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('location', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'location')
    ### end Alembic commands ###
