"""add table out

Revision ID: 2ac8a3b03cdb
Revises: 415be74d0a74
Create Date: 2015-08-03 14:10:45.723027

"""

# revision identifiers, used by Alembic.
revision = '2ac8a3b03cdb'
down_revision = '415be74d0a74'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('meeting_s', sa.Text(), nullable=True),
    sa.Column('m_persion', sa.String(length=200), nullable=True),
    sa.Column('creator_type', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_out')
    ### end Alembic commands ###
