"""add colum finish_time and framework_order

Revision ID: 2adc8cc5104c
Revises: 3302008262bc
Create Date: 2015-10-20 11:14:37.829380

"""

# revision identifiers, used by Alembic.
revision = '2adc8cc5104c'
down_revision = '3302008262bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_framework_order', sa.Column('finish_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_framework_order', 'finish_time')
    ### end Alembic commands ###
