"""add colum agents in bra_forwork_order

Revision ID: 2bf047e8c1b8
Revises: 1e5ec46c547b
Create Date: 2015-03-17 18:27:28.717740

"""

# revision identifiers, used by Alembic.
revision = '2bf047e8c1b8'
down_revision = '1e5ec46c547b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('framework_order_agents',
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('framework_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['framework_order_id'], ['bra_framework_order.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('framework_order_agents')
    ### end Alembic commands ###
