"""add Unique in bra_agent_media_rebate

Revision ID: 2c5961b7af9c
Revises: 2b8d9016a14b
Create Date: 2016-08-03 17:12:29.506987

"""

# revision identifiers, used by Alembic.
revision = '2c5961b7af9c'
down_revision = '2b8d9016a14b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_agent_media_year_rebate', 'bra_agent_media_rebate', ['agent_id', 'media_id', 'year'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_agent_media_year_rebate', 'bra_agent_media_rebate')
    ### end Alembic commands ###
