"""add colum team_leaders in user table

Revision ID: 2ca1656e9a54
Revises: aa785597071
Create Date: 2015-05-05 12:11:00.994504

"""

# revision identifiers, used by Alembic.
revision = '2ca1656e9a54'
down_revision = 'aa785597071'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_leaders',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('leader_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['leader_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'leader_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_leaders')
    ### end Alembic commands ###
