"""add colum back_money_status in client_order

Revision ID: 2edc21c21560
Revises: 107e121a1249
Create Date: 2015-03-31 11:21:35.718951

"""

# revision identifiers, used by Alembic.
revision = '2edc21c21560'
down_revision = '107e121a1249'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_client_order', sa.Column('back_money_status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_client_order', 'back_money_status')
    ### end Alembic commands ###
