"""add table back invoice rebate

Revision ID: 2ef8bd1eb23e
Revises: 4e86dc3c8dd1
Create Date: 2015-05-18 11:16:32.491724

"""

# revision identifiers, used by Alembic.
revision = '2ef8bd1eb23e'
down_revision = '4e86dc3c8dd1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bra_client_order_back_invoice_rebate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.Column('num', sa.String(length=100), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('back_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], ['bra_client_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bra_client_order_back_invoice_rebate')
    ### end Alembic commands ###
