"""add column summary in user_okr

Revision ID: 2f6ba45519b0
Revises: 4d106603aabb
Create Date: 2016-07-18 16:53:51.358714

"""

# revision identifiers, used by Alembic.
revision = '2f6ba45519b0'
down_revision = '4d106603aabb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_okr', sa.Column('summary', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_okr', 'summary')
    ### end Alembic commands ###
