"""add colum in out

Revision ID: 30d515932617
Revises: 2ac8a3b03cdb
Create Date: 2015-08-03 14:48:41.743084

"""

# revision identifiers, used by Alembic.
revision = '30d515932617'
down_revision = '2ac8a3b03cdb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_out', sa.Column('m_persion_type', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_out', 'm_persion_type')
    ### end Alembic commands ###
