"""add colum total_score in kpi table

Revision ID: 32064b0b2eff
Revises: 25ec7a844a6
Create Date: 2015-07-21 11:09:45.785751

"""

# revision identifiers, used by Alembic.
revision = '32064b0b2eff'
down_revision = '25ec7a844a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preformance_evaluation', sa.Column('total_score', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preformance_evaluation', 'total_score')
    ### end Alembic commands ###
