"""add colum framework_order_id in searchad_client_order

Revision ID: 325177319c0f
Revises: 1a7a0381a06b
Create Date: 2015-08-31 12:42:27.065340

"""

# revision identifiers, used by Alembic.
revision = '325177319c0f'
down_revision = '1a7a0381a06b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('searchAd_bra_client_order', sa.Column('framework_order_id', sa.Integer(), server_default='0', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('searchAd_bra_client_order', 'framework_order_id')
    ### end Alembic commands ###
