"""add colum mediuas in case

Revision ID: 32893235c1b7
Revises: 494b42ee0c35
Create Date: 2016-08-08 11:20:12.087155

"""

# revision identifiers, used by Alembic.
revision = '32893235c1b7'
down_revision = '494b42ee0c35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_medias',
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['bra_case.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_medias')
    ### end Alembic commands ###
