"""add colum qiut_date and cellphone in user

Revision ID: 3302008262bc
Revises: 47f5c5f9d5d9
Create Date: 2015-10-19 11:14:35.120264

"""

# revision identifiers, used by Alembic.
revision = '3302008262bc'
down_revision = '47f5c5f9d5d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cellphone', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('quit_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'quit_date')
    op.drop_column('user', 'cellphone')
    ### end Alembic commands ###
