"""add table other_cost in order

Revision ID: 33953b5d85ee
Revises: 1f099cff032c
Create Date: 2016-03-15 16:37:37.256627

"""

# revision identifiers, used by Alembic.
revision = '33953b5d85ee'
down_revision = '1f099cff032c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bra_client_order_other_cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('invoice', sa.String(length=100), nullable=True),
    sa.Column('on_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], ['bra_client_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bra_douban_order_other_cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('douban_order_id', sa.Integer(), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('invoice', sa.String(length=100), nullable=True),
    sa.Column('on_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['douban_order_id'], ['bra_douban_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bra_douban_order_other_cost')
    op.drop_table('bra_client_order_other_cost')
    ### end Alembic commands ###
