"""rm framework client medium

Revision ID: 33d43f18965c
Revises: 3f8b6443b09a
Create Date: 2014-12-30 10:44:10.104679

"""

# revision identifiers, used by Alembic.
revision = '33d43f18965c'
down_revision = '3f8b6443b09a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'framework')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('framework', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    ### end Alembic commands ###
