"""add colum level in media

Revision ID: 348d461214e9
Revises: 21b448cb6a09
Create Date: 2016-08-03 11:59:33.380745

"""

# revision identifiers, used by Alembic.
revision = '348d461214e9'
down_revision = '21b448cb6a09'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('level', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'level')
    ### end Alembic commands ###
