"""add colum media in medium_invoice

Revision ID: 36ec9d24c5c1
Revises: 32893235c1b7
Create Date: 2016-08-08 14:05:28.669605

"""

# revision identifiers, used by Alembic.
revision = '36ec9d24c5c1'
down_revision = '32893235c1b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_medium_invoice', sa.Column('media_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_medium_invoice', 'media_id')
    ### end Alembic commands ###
