"""add outsource target type

Revision ID: 37d04625d281
Revises: 4b090ba8dc7f
Create Date: 2015-01-29 15:58:58.582322

"""

# revision identifiers, used by Alembic.
revision = '37d04625d281'
down_revision = '4b090ba8dc7f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('out_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'out_source_target', sa.Column('type', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'out_source_target', 'type')
    op.drop_table('out_source')
    ### end Alembic commands ###
