"""add outsource column pay_num

Revision ID: 38420eddd91c
Revises: 257ca960c779
Create Date: 2015-03-24 17:42:02.726021

"""

# revision identifiers, used by Alembic.
revision = '38420eddd91c'
down_revision = '257ca960c779'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('out_source', sa.Column('pay_num', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('out_source', 'pay_num')
    ### end Alembic commands ###
