"""rm unused colum

Revision ID: 38b0a4ee97ac
Revises: 190bb0293563
Create Date: 2014-12-15 17:13:00.939201

"""

# revision identifiers, used by Alembic.
revision = '38b0a4ee97ac'
down_revision = '190bb0293563'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_order', 'contract_status')
    op.drop_column('bra_order', 'money')
    op.drop_column('bra_order', 'client_end')
    op.drop_column('bra_order', 'contract')
    op.drop_column('bra_order', 'client_start')
    op.drop_column('bra_order', 'reminde_date')
    op.drop_column('bra_order', 'contract_type')
    op.drop_column('bra_order', 'resource_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_order', sa.Column('resource_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bra_order', sa.Column('contract_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bra_order', sa.Column('reminde_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('bra_order', sa.Column('client_start', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('bra_order', sa.Column('contract', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('bra_order', sa.Column('client_end', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('bra_order', sa.Column('money', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bra_order', sa.Column('contract_status', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
