"""add table bra_intention_salers

Revision ID: 394e07b25411
Revises: 2a96699469d7
Create Date: 2016-04-14 15:11:14.690400

"""

# revision identifiers, used by Alembic.
revision = '394e07b25411'
down_revision = '2a96699469d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intention_order_agent_sales',
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('intent_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['intent_order_id'], ['bra_intention_order.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['user.id'], )
    )
    op.create_table('intention_order_direct_sales',
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('intent_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['intent_order_id'], ['bra_intention_order.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intention_order_direct_sales')
    op.drop_table('intention_order_agent_sales')
    ### end Alembic commands ###
