"""add table

Revision ID: 3accc50b76
Revises: 1f6e397add11
Create Date: 2016-09-05 18:43:19.917403

"""

# revision identifiers, used by Alembic.
revision = '3accc50b76'
down_revision = '1f6e397add11'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searchAd_bra_bill_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_order_bill_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('bank_id', sa.String(length=50), nullable=True),
    sa.Column('bank', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('invoice_type', sa.Integer(), nullable=True),
    sa.Column('invoice_status', sa.Integer(), nullable=True),
    sa.Column('invoice_num', sa.String(length=200), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('back_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_order_bill_id'], ['searchad_bra_client_order_bill.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('searchAd_bra_bill_invoice')
    ### end Alembic commands ###
