"""add table other_nianhui

Revision ID: 3b31071e1f4d
Revises: 33953b5d85ee
Create Date: 2016-03-31 12:25:05.449094

"""

# revision identifiers, used by Alembic.
revision = '3b31071e1f4d'
down_revision = '33953b5d85ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('other_nianhui',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('ids', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('other_nianhui')
    ### end Alembic commands ###
