"""add table bra_douban_order_executive_report

Revision ID: 3b68f290e28d
Revises: 4aaa96eac96a
Create Date: 2015-05-27 10:52:26.499404

"""

# revision identifiers, used by Alembic.
revision = '3b68f290e28d'
down_revision = '4aaa96eac96a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bra_douban_order_executive_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('douban_order_id', sa.Integer(), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('month_day', sa.DateTime(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['douban_order_id'], ['bra_douban_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('douban_order_id', 'month_day', name='_douban_order_month_day')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bra_douban_order_executive_report')
    ### end Alembic commands ###
