"""add colum status in client_order

Revision ID: 3c454a88604e
Revises: 5ad00f1c9dc3
Create Date: 2015-03-30 17:47:58.988880

"""

# revision identifiers, used by Alembic.
revision = '3c454a88604e'
down_revision = '5ad00f1c9dc3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_client_order', sa.Column('status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_client_order', 'status')
    ### end Alembic commands ###
