"""rm unused colum

Revision ID: 3dc05209d727
Revises: 38b0a4ee97ac
Create Date: 2014-12-16 11:28:12.857594

"""

# revision identifiers, used by Alembic.
revision = '3dc05209d727'
down_revision = '38b0a4ee97ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_order_users_designerer')
    op.drop_table('client_order_users_planer')
    op.drop_table('order_direct_sales')
    op.drop_table('client_order_users_operater')
    op.drop_table('order_agent_sales')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_agent_sales',
    sa.Column('agent_sale_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_sale_id'], [u'user.id'], name=u'order_agent_sales_agent_sale_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], [u'bra_order.id'], name=u'order_agent_sales_order_id_fkey')
    )
    op.create_table('client_order_users_operater',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], [u'bra_client_order.id'], name=u'client_order_users_operater_client_order_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'client_order_users_operater_user_id_fkey')
    )
    op.create_table('order_direct_sales',
    sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], [u'bra_order.id'], name=u'order_direct_sales_order_id_fkey'),
    sa.ForeignKeyConstraint(['sale_id'], [u'user.id'], name=u'order_direct_sales_sale_id_fkey')
    )
    op.create_table('client_order_users_planer',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], [u'bra_client_order.id'], name=u'client_order_users_planer_client_order_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'client_order_users_planer_user_id_fkey')
    )
    op.create_table('client_order_users_designerer',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], [u'bra_client_order.id'], name=u'client_order_users_designerer_client_order_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'client_order_users_designerer_user_id_fkey')
    )
    ### end Alembic commands ###
