"""add colum position in user

Revision ID: 3f07c7473322
Revises: 29b6d6f2b33
Create Date: 2015-11-03 10:39:52.468542

"""

# revision identifiers, used by Alembic.
revision = '3f07c7473322'
down_revision = '29b6d6f2b33'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('position', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'position')
    ### end Alembic commands ###
