"""add colum in table out joiners

Revision ID: 3f111b604d89
Revises: 138f333940e4
Create Date: 2015-08-10 17:16:48.260859

"""

# revision identifiers, used by Alembic.
revision = '3f111b604d89'
down_revision = '138f333940e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('out_joiners',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('out_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['out_id'], ['user_out.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('out_joiners')
    ### end Alembic commands ###
