"""add column rate_day in user_leave

Revision ID: 3f778837a66f
Revises: 1c69f11458de
Create Date: 2015-05-08 11:28:20.471661

"""

# revision identifiers, used by Alembic.
revision = '3f778837a66f'
down_revision = '1c69f11458de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_leave', sa.Column('rate_day', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_leave', 'rate_day')
    ### end Alembic commands ###
