"""add colum assistant in order

Revision ID: 400d45dd66c0
Revises: 56382edda779
Create Date: 2016-04-12 15:50:36.445813

"""

# revision identifiers, used by Alembic.
revision = '400d45dd66c0'
down_revision = '56382edda779'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('douban_order_assistant_sales',
    sa.Column('assistant_sale_id', sa.Integer(), nullable=True),
    sa.Column('douban_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assistant_sale_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['douban_order_id'], ['bra_douban_order.id'], )
    )
    op.create_table('client_order_assistant_sales',
    sa.Column('assistant_sale_id', sa.Integer(), nullable=True),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assistant_sale_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['client_order_id'], ['bra_client_order.id'], )
    )
    op.create_table('framework_order_assistant_sales',
    sa.Column('assistant_sale_id', sa.Integer(), nullable=True),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assistant_sale_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['client_order_id'], ['bra_framework_order.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('framework_order_assistant_sales')
    op.drop_table('client_order_assistant_sales')
    op.drop_table('douban_order_assistant_sales')
    ### end Alembic commands ###
