"""add colum status in douban_order

Revision ID: 4038a43c89c
Revises: 3c454a88604e
Create Date: 2015-03-30 18:01:13.054949

"""

# revision identifiers, used by Alembic.
revision = '4038a43c89c'
down_revision = '3c454a88604e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_douban_order', sa.Column('status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_douban_order', 'status')
    ### end Alembic commands ###
