"""add table person notice

Revision ID: 403f1953348b
Revises: 2e9d37b5c0d5
Create Date: 2015-12-07 16:56:13.435566

"""

# revision identifiers, used by Alembic.
revision = '403f1953348b'
down_revision = '2e9d37b5c0d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_notice')
    ### end Alembic commands ###
