"""add colum media in some tabales

Revision ID: 40501173f0b8
Revises: 2c5961b7af9c
Create Date: 2016-08-05 10:23:31.828271

"""

# revision identifiers, used by Alembic.
revision = '40501173f0b8'
down_revision = '2c5961b7af9c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_client_medium_order', sa.Column('media_id', sa.Integer(), nullable=True))
    op.add_column('bra_intention_order', sa.Column('media_id', sa.Integer(), nullable=True))
    op.add_column('bra_medium_rebate_invoice', sa.Column('media_id', sa.Integer(), nullable=True))
    op.add_column('bra_order', sa.Column('media_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_order', 'media_id')
    op.drop_column('bra_medium_rebate_invoice', 'media_id')
    op.drop_column('bra_intention_order', 'media_id')
    op.drop_column('bra_client_medium_order', 'media_id')
    ### end Alembic commands ###
