"""add table searchad_bra_rebate_order

Revision ID: 4154756e95ae
Revises: 202e8dc4ce45
Create Date: 2015-11-16 15:08:03.573658

"""

# revision identifiers, used by Alembic.
revision = '4154756e95ae'
down_revision = '202e8dc4ce45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searchad_bra_rebate_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('campaign', sa.String(length=100), nullable=True),
    sa.Column('contract', sa.String(length=100), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.Column('medium_CPM', sa.Integer(), nullable=True),
    sa.Column('sale_CPM', sa.Integer(), nullable=True),
    sa.Column('contract_type', sa.Integer(), nullable=True),
    sa.Column('client_start', sa.Date(), nullable=True),
    sa.Column('client_end', sa.Date(), nullable=True),
    sa.Column('reminde_date', sa.Date(), nullable=True),
    sa.Column('contract_status', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('resource_type', sa.Integer(), nullable=True),
    sa.Column('sale_type', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('finish_time', sa.DateTime(), nullable=True),
    sa.Column('back_money_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['searchAd_agent.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['searchAd_client.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bra_searchad_rebate_order_executive_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rebate_order_id', sa.Integer(), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('month_day', sa.DateTime(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rebate_order_id'], ['searchad_bra_rebate_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rebate_order_id', 'month_day', name='_searchad_rebate_order_month_day')
    )
    op.create_table('bra_rebate_order_back_money',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rebate_order_id', sa.Integer(), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('back_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rebate_order_id'], ['searchad_bra_rebate_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchad_rebate_order_sales',
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('searchad_rebate_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['searchad_rebate_order_id'], ['searchad_bra_rebate_order.id'], )
    )
    op.create_table('searchad_bra_rebate_order_reject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rebate_order_id', sa.Integer(), nullable=True),
    sa.Column('reject_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rebate_order_id'], ['searchad_bra_rebate_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rebate_order_id', 'reject_time', name='_searchad_rebate_order_reject_time')
    )
    op.create_table('searchad_rebate_order_replace_sales',
    sa.Column('replace_sale_id', sa.Integer(), nullable=True),
    sa.Column('searchad_rebate_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['replace_sale_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['searchad_rebate_order_id'], ['searchad_bra_rebate_order.id'], )
    )
    op.create_table('searchad_rebate_orderusers_designerer',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('searchad_rebate_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['searchad_rebate_order_id'], ['searchad_bra_rebate_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('searchad_rebate_order_users_planer',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('searchad_rebate_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['searchad_rebate_order_id'], ['searchad_bra_rebate_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('searchad_rebate_order_users_operater',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('searchad_rebate_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['searchad_rebate_order_id'], ['searchad_bra_rebate_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('bra_rebate_order_back_invoice_rebate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rebate_order_id', sa.Integer(), nullable=True),
    sa.Column('num', sa.String(length=100), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('back_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rebate_order_id'], ['searchad_bra_rebate_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bra_rebate_order_back_invoice_rebate')
    op.drop_table('searchad_rebate_order_users_operater')
    op.drop_table('searchad_rebate_order_users_planer')
    op.drop_table('searchad_rebate_orderusers_designerer')
    op.drop_table('searchad_rebate_order_replace_sales')
    op.drop_table('searchad_bra_rebate_order_reject')
    op.drop_table('searchad_rebate_order_sales')
    op.drop_table('bra_rebate_order_back_money')
    op.drop_table('bra_searchad_rebate_order_executive_report')
    op.drop_table('searchad_bra_rebate_order')
    ### end Alembic commands ###
