"""add douban back money

Revision ID: 415be74d0a74
Revises: 29946b1da9ac
Create Date: 2015-07-30 12:29:22.211956

"""

# revision identifiers, used by Alembic.
revision = '415be74d0a74'
down_revision = '29946b1da9ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bra_douban_order_back_invoice_rebate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('douban_order_id', sa.Integer(), nullable=True),
    sa.Column('num', sa.String(length=100), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('back_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['douban_order_id'], ['bra_douban_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bra_douban_order_back_money',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('douban_order_id', sa.Integer(), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('back_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['douban_order_id'], ['bra_douban_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'bra_douban_order', sa.Column('back_money_status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'bra_douban_order', 'back_money_status')
    op.drop_table('bra_douban_order_back_money')
    op.drop_table('bra_douban_order_back_invoice_rebate')
    ### end Alembic commands ###
