"""add table user_leave

Revision ID: 421199db1d88
Revises: 1aeab9b2d6a2
Create Date: 2015-04-24 11:48:17.860964

"""

# revision identifiers, used by Alembic.
revision = '421199db1d88'
down_revision = '1aeab9b2d6a2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_leave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('start', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_send_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('leave_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['leave_id'], ['user_leave.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leave_send_users')
    op.drop_table('user_leave')
    ### end Alembic commands ###
