"""add colum desc in case

Revision ID: 42533addb511
Revises: 19951205f73c
Create Date: 2015-09-24 11:01:29.757594

"""

# revision identifiers, used by Alembic.
revision = '42533addb511'
down_revision = '19951205f73c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_case', sa.Column('desc', sa.String(length=300), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_case', 'desc')
    ### end Alembic commands ###
