"""delete index

Revision ID: 42aafca548a3
Revises: 219246606072
Create Date: 2016-07-28 14:40:34.983107

"""

# revision identifiers, used by Alembic.
revision = '42aafca548a3'
down_revision = '219246606072'

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(u'_agent_medium_rebate_year', 'bra_agent_medium_rebate')
    # op.drop_index('_agent_medium_rebate_year', table_name='bra_agent_medium_rebate')
    ### end Alembic commands ###


def downgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('_agent_medium_rebate_year', 'bra_agent_medium_rebate', ['agent_id', 'medium_id', 'year'], unique=True)
    # op.create_unique_constraint(u'_agent_medium_rebate_year', 'bra_agent_medium_rebate', ['agent_id', 'medium_id', 'year'])
    ### end Alembic commands ###
