"""add table order_reject 

Revision ID: 42d521195c39
Revises: 3b68f290e28d
Create Date: 2015-06-01 15:36:43.623162

"""

# revision identifiers, used by Alembic.
revision = '42d521195c39'
down_revision = '3b68f290e28d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bra_douban_order_reject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('douban_order_id', sa.Integer(), nullable=True),
    sa.Column('reject_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['douban_order_id'], ['bra_douban_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('douban_order_id', 'reject_time', name='_douban_order_reject_time')
    )
    op.create_table('bra_client_order_reject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.Column('reject_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], ['bra_client_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id', 'reject_time', name='_client_order_reject_time')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bra_client_order_reject')
    op.drop_table('bra_douban_order_reject')
    ### end Alembic commands ###
