"""add table user_hand_book

Revision ID: 4472ec0db741
Revises: 30076edcb23f
Create Date: 2015-11-12 10:40:24.868376

"""

# revision identifiers, used by Alembic.
revision = '4472ec0db741'
down_revision = '30076edcb23f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_hand_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='_user_hand_book_user_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_hand_book')
    ### end Alembic commands ###
