"""add table medium_group

Revision ID: 44da80b9e5ad
Revises: 4d106603aabb
Create Date: 2016-07-13 16:23:38.004985

"""

# revision identifiers, used by Alembic.
revision = '44da80b9e5ad'
down_revision = '4d106603aabb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medium_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('tax_num', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('phone_num', sa.String(length=100), nullable=True),
    sa.Column('bank', sa.String(length=100), nullable=True),
    sa.Column('bank_num', sa.String(length=100), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bra_medium_group_rebate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medium_group_id', sa.Integer(), nullable=True),
    sa.Column('rebate', sa.Float(), nullable=True),
    sa.Column('year', sa.Date(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['medium_group_id'], ['medium_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medium_group_id', 'year', name='_medium_group_rebate_year')
    )
    op.add_column(u'medium', sa.Column('medium_group_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'medium', 'medium_group_id')
    op.drop_table('bra_medium_group_rebate')
    op.drop_table('medium_group')
    ### end Alembic commands ###
