"""delivery

Revision ID: 4724e30f478b
Revises: 19f503b46236
Create Date: 2014-10-08 06:22:22.093793

"""

# revision identifiers, used by Alembic.
revision = '4724e30f478b'
down_revision = '19f503b46236'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('delivery_type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery')
    ### end Alembic commands ###
