"""medium add sale money

Revision ID: 475db38a4544
Revises: 1d0f10b0054a
Create Date: 2015-01-13 18:41:30.720807

"""

# revision identifiers, used by Alembic.
revision = '475db38a4544'
down_revision = '1d0f10b0054a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_order', sa.Column('sale_money', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_order', 'sale_money')
    ### end Alembic commands ###
