"""order colum update

Revision ID: 4823715e2dc4
Revises: 4fb3bd582b7c
Create Date: 2014-12-05 14:17:10.321000

"""

# revision identifiers, used by Alembic.
revision = '4823715e2dc4'
down_revision = '4fb3bd582b7c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_order', sa.Column('client_end', sa.Date(), nullable=True))
    op.add_column('bra_order', sa.Column('client_start', sa.Date(), nullable=True))
    op.add_column('bra_order', sa.Column('contract_status', sa.Integer(), nullable=True))
    op.add_column('bra_order', sa.Column('contract_type', sa.Integer(), nullable=True))
    op.add_column('bra_order', sa.Column('medium_contract', sa.String(length=100), nullable=True))
    op.add_column('bra_order', sa.Column('medium_end', sa.Date(), nullable=True))
    op.add_column('bra_order', sa.Column('medium_money', sa.Integer(), nullable=True))
    op.add_column('bra_order', sa.Column('medium_start', sa.Date(), nullable=True))
    op.add_column('bra_order', sa.Column('reminde_date', sa.Date(), nullable=True))
    op.add_column('bra_order', sa.Column('resource_type', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_order', 'resource_type')
    op.drop_column('bra_order', 'reminde_date')
    op.drop_column('bra_order', 'medium_start')
    op.drop_column('bra_order', 'medium_money')
    op.drop_column('bra_order', 'medium_end')
    op.drop_column('bra_order', 'medium_contract')
    op.drop_column('bra_order', 'contract_type')
    op.drop_column('bra_order', 'contract_status')
    op.drop_column('bra_order', 'client_start')
    op.drop_column('bra_order', 'client_end')
    ### end Alembic commands ###
