"""add colum level in medium

Revision ID: 4848d1d9da29
Revises: 25ded65f110d
Create Date: 2015-12-03 16:37:58.228047

"""

# revision identifiers, used by Alembic.
revision = '4848d1d9da29'
down_revision = '25ded65f110d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medium', sa.Column('level', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medium', 'level')
    ### end Alembic commands ###
