"""add colum in search frameworkorder

Revision ID: 4b20f61b4f72
Revises: 12c0a209e51a
Create Date: 2016-01-18 15:42:29.979180

"""

# revision identifiers, used by Alembic.
revision = '4b20f61b4f72'
down_revision = '12c0a209e51a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_searchAd_framework_order', sa.Column('client_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_searchAd_framework_order', 'client_id')
    ### end Alembic commands ###
