"""money int to float

Revision ID: 4bfb38542cc6
Revises: 141568aa0c4c
Create Date: 2016-03-08 17:58:10.406609

"""

# revision identifiers, used by Alembic.
revision = '4bfb38542cc6'
down_revision = '141568aa0c4c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
