"""add team admins

Revision ID: 4d534110cc55
Revises: 1fd3e0a5fd14
Create Date: 2015-01-05 14:11:25.676070

"""

# revision identifiers, used by Alembic.
revision = '4d534110cc55'
down_revision = '1fd3e0a5fd14'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_admin_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_admin_users')
    ### end Alembic commands ###
