"""add colum b_type in media

Revision ID: 4d8394f3941
Revises: 26fbbeeaf791
Create Date: 2016-08-19 10:45:58.176730

"""

# revision identifiers, used by Alembic.
revision = '4d8394f3941'
down_revision = '26fbbeeaf791'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('b_type', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'b_type')
    ### end Alembic commands ###
