"""add launch_strategy in adposition

Revision ID: 4fb3bd582b7c
Revises: 13a68d6fa649
Create Date: 2014-10-10 15:07:16.742408

"""

# revision identifiers, used by Alembic.
revision = '4fb3bd582b7c'
down_revision = '13a68d6fa649'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_position', sa.Column('launch_strategy', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad_position', 'launch_strategy')
    ### end Alembic commands ###
