"""rm framework medium

Revision ID: 50009ec44238
Revises: 33d43f18965c
Create Date: 2014-12-30 10:59:46.467798

"""

# revision identifiers, used by Alembic.
revision = '50009ec44238'
down_revision = '33d43f18965c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medium', 'framework')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medium', sa.Column('framework', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    ### end Alembic commands ###
