"""add table user_out_report

Revision ID: 5267491214fe
Revises: 3604d3062fe2
Create Date: 2016-02-02 10:42:02.171633

"""

# revision identifiers, used by Alembic.
revision = '5267491214fe'
down_revision = '3604d3062fe2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_out_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('meeting_s', sa.Text(), nullable=True),
    sa.Column('persions', sa.String(length=300), nullable=True),
    sa.Column('m_persion', sa.String(length=200), nullable=True),
    sa.Column('m_persion_type', sa.Integer(), nullable=True),
    sa.Column('creator_type', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('out_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['out_id'], ['user_out.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_out_report_end_time'), 'user_out_report', ['end_time'], unique=False)
    op.create_index(op.f('ix_user_out_report_start_time'), 'user_out_report', ['start_time'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_out_report_start_time'), table_name='user_out_report')
    op.drop_index(op.f('ix_user_out_report_end_time'), table_name='user_out_report')
    op.drop_table('user_out_report')
    ### end Alembic commands ###
