"""add colum cc in bra_planning

Revision ID: 53b27f3f5952
Revises: 27bdd1d4ad8c
Create Date: 2016-01-11 18:07:36.863743

"""

# revision identifiers, used by Alembic.
revision = '53b27f3f5952'
down_revision = '27bdd1d4ad8c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_planning_bref', sa.Column('cc', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_planning_bref', 'cc')
    ### end Alembic commands ###
