"""add money

Revision ID: 5427463a333f
Revises: 254667d5628a
Create Date: 2015-01-13 15:32:50.784908

"""

# revision identifiers, used by Alembic.
revision = '5427463a333f'
down_revision = '254667d5628a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_associated_douban_order', sa.Column('money', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_associated_douban_order', 'money')
    ### end Alembic commands ###
