"""add colum medium_group in client_medium_order

Revision ID: 544e4717c5cc
Revises: 1e75cd1c8b34
Create Date: 2016-08-01 12:26:40.361143

"""

# revision identifiers, used by Alembic.
revision = '544e4717c5cc'
down_revision = '1e75cd1c8b34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_client_medium_order', sa.Column('medium_group_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_client_medium_order', 'medium_group_id')
    ### end Alembic commands ###
