"""add table client_medium_order

Revision ID: 558ceb2d5be8
Revises: a0254c52e31
Create Date: 2016-05-26 16:00:18.834832

"""

# revision identifiers, used by Alembic.
revision = '558ceb2d5be8'
down_revision = 'a0254c52e31'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bra_client_medium_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('campaign', sa.String(length=100), nullable=True),
    sa.Column('contract', sa.String(length=100), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('medium_CPM', sa.Integer(), nullable=True),
    sa.Column('sale_CPM', sa.Integer(), nullable=True),
    sa.Column('contract_type', sa.Integer(), nullable=True),
    sa.Column('client_start', sa.Date(), nullable=True),
    sa.Column('client_end', sa.Date(), nullable=True),
    sa.Column('client_start_year', sa.Integer(), nullable=True),
    sa.Column('client_end_year', sa.Integer(), nullable=True),
    sa.Column('reminde_date', sa.Date(), nullable=True),
    sa.Column('contract_status', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('resource_type', sa.Integer(), nullable=True),
    sa.Column('sale_type', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('finish_time', sa.DateTime(), nullable=True),
    sa.Column('back_money_status', sa.Integer(), nullable=True),
    sa.Column('self_agent_rebate', sa.String(length=20), nullable=True),
    sa.Column('medium_id', sa.Integer(), nullable=True),
    sa.Column('medium_money', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['medium_id'], ['medium.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bra_client_medium_order_client_end_year'), 'bra_client_medium_order', ['client_end_year'], unique=False)
    op.create_index(op.f('ix_bra_client_medium_order_client_start_year'), 'bra_client_medium_order', ['client_start_year'], unique=False)
    op.create_table('bra_client_medium_order_back_money',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_medium_order_id', sa.Integer(), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('back_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_medium_order_id'], ['bra_client_medium_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_medium_order_direct_sales',
    sa.Column('direct_sale_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['direct_sale_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['bra_client_medium_order.id'], )
    )
    op.create_table('client_medium_order_assistant_sales',
    sa.Column('assistant_sale_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assistant_sale_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['bra_client_medium_order.id'], )
    )
    op.create_table('bra_cleint_medium_order_back_invoice_rebate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_medium_order_id', sa.Integer(), nullable=True),
    sa.Column('num', sa.String(length=100), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('back_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_medium_order_id'], ['bra_client_medium_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_medium_order_agent_sales',
    sa.Column('agent_sale_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_sale_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['bra_client_medium_order.id'], )
    )
    op.create_table('client_medium_order_users_planer',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['bra_client_medium_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('client_medium_order_users_operater',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['bra_client_medium_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('client_medium_order_replace_sales',
    sa.Column('replace_sale_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['bra_client_medium_order.id'], ),
    sa.ForeignKeyConstraint(['replace_sale_id'], ['user.id'], )
    )
    op.create_table('client_medium_order_users_designerer',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['bra_client_medium_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_medium_order_users_designerer')
    op.drop_table('client_medium_order_replace_sales')
    op.drop_table('client_medium_order_users_operater')
    op.drop_table('client_medium_order_users_planer')
    op.drop_table('client_medium_order_agent_sales')
    op.drop_table('bra_cleint_medium_order_back_invoice_rebate')
    op.drop_table('client_medium_order_assistant_sales')
    op.drop_table('client_medium_order_direct_sales')
    op.drop_table('bra_client_medium_order_back_money')
    op.drop_index(op.f('ix_bra_client_medium_order_client_start_year'), table_name='bra_client_medium_order')
    op.drop_index(op.f('ix_bra_client_medium_order_client_end_year'), table_name='bra_client_medium_order')
    op.drop_table('bra_client_medium_order')
    ### end Alembic commands ###
