"""add table client_order_executive_report

Revision ID: 55b1a1fb7f8e
Revises: 2ef8bd1eb23e
Create Date: 2015-05-19 11:44:18.029179

"""

# revision identifiers, used by Alembic.
revision = '55b1a1fb7f8e'
down_revision = '2ef8bd1eb23e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bra_client_order_executive_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('month_day', sa.DateTime(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], ['bra_client_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id', 'month_day', name='_client_order_month_day')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bra_client_order_executive_report')
    ### end Alembic commands ###
