"""add colum finish_time in medium_order

Revision ID: 5810fb3e73e5
Revises: 42aa75ed3314
Create Date: 2015-09-06 16:49:17.764317

"""

# revision identifiers, used by Alembic.
revision = '5810fb3e73e5'
down_revision = '42aa75ed3314'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_order', sa.Column('finish_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_order', 'finish_time')
    ### end Alembic commands ###
