"""add colum channel_type in search_client_order

Revision ID: 59490ed174d0
Revises: 400d45dd66c0
Create Date: 2016-04-12 16:17:42.573772

"""

# revision identifiers, used by Alembic.
revision = '59490ed174d0'
down_revision = '400d45dd66c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('searchAd_bra_order', sa.Column('channel_type', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('searchAd_bra_order', 'channel_type')
    ### end Alembic commands ###
