"""add colum in out

Revision ID: 5aa295a4a7d2
Revises: 30d515932617
Create Date: 2015-08-04 11:36:26.316421

"""

# revision identifiers, used by Alembic.
revision = '5aa295a4a7d2'
down_revision = '30d515932617'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_out', sa.Column('address', sa.String(length=300), nullable=True))
    op.add_column('user_out', sa.Column('persions', sa.String(length=300), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_out', 'persions')
    op.drop_column('user_out', 'address')
    ### end Alembic commands ###
