"""fix invoice table

Revision ID: 5aae8aec8c5f
Revises: 35fc1226573e
Create Date: 2015-03-18 12:25:11.611279

"""

# revision identifiers, used by Alembic.
revision = '5aae8aec8c5f'
down_revision = '35fc1226573e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
