"""add colum medium_group in invoice

Revision ID: 5ab57895e7c2
Revises: 544e4717c5cc
Create Date: 2016-08-01 15:51:41.405059

"""

# revision identifiers, used by Alembic.
revision = '5ab57895e7c2'
down_revision = '544e4717c5cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_medium_invoice', sa.Column('medium_group_id', sa.Integer(), nullable=True))
    op.add_column('bra_medium_rebate_invoice', sa.Column('medium_group_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_medium_rebate_invoice', 'medium_group_id')
    op.drop_column('bra_medium_invoice', 'medium_group_id')
    ### end Alembic commands ###
