"""add column pay_money in medium

Revision ID: 5ad00f1c9dc3
Revises: 2f81ab70c654
Create Date: 2015-03-30 15:13:56.981250

"""

# revision identifiers, used by Alembic.
revision = '5ad00f1c9dc3'
down_revision = '2f81ab70c654'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_medium_invoice', sa.Column('pay_money', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_medium_invoice', 'pay_money')
    ### end Alembic commands ###
