"""add unique performance performance_user

Revision ID: 7c2553bead
Revises: 2a438435c68e
Create Date: 2015-08-26 15:45:13.442117

"""

# revision identifiers, used by Alembic.
revision = '7c2553bead'
down_revision = '2a438435c68e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_commission_user_year', 'commission', ['user_id', 'year'])
    op.create_unique_constraint('_performance_location_year_q', 'performance', ['location', 'year', 'q_month'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_performance_location_year_q', 'performance')
    op.drop_constraint('_commission_user_year', 'commission')
    ### end Alembic commands ###
