"""add table outsource_report

Revision ID: 8352e011c85
Revises: 103fe6b97f9b
Create Date: 2015-06-17 10:38:35.546925

"""

# revision identifiers, used by Alembic.
revision = '8352e011c85'
down_revision = '103fe6b97f9b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bra_outsource_executive_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('outsource_id', sa.Integer(), nullable=True),
    sa.Column('otype', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('subtype', sa.Integer(), nullable=True),
    sa.Column('invoice', sa.Boolean(), nullable=True),
    sa.Column('num', sa.Float(), nullable=True),
    sa.Column('pay_num', sa.Float(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('month_day', sa.DateTime(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['out_source_target.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outsource_id', 'otype', 'month_day', name='_outsource_month_day_report')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bra_outsource_executive_report')
    ### end Alembic commands ###
