"""add attachment status

Revision ID: 9791f847e
Revises: 3eeb53fc0904
Create Date: 2014-12-30 12:39:12.778119

"""

# revision identifiers, used by Alembic.
revision = '9791f847e'
down_revision = '3eeb53fc0904'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_attachment', sa.Column('attachment_status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_attachment', 'attachment_status')
    ### end Alembic commands ###
