"""fix add invoice table

Revision ID: 993b80c198c
Revises: 12b8c33ce34a
Create Date: 2015-03-18 17:37:01.624892

"""

# revision identifiers, used by Alembic.
revision = '993b80c198c'
down_revision = '12b8c33ce34a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bra_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('bank_id', sa.String(length=20), nullable=True),
    sa.Column('bank', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('invoice_type', sa.Integer(), nullable=True),
    sa.Column('invoice_status', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], ['bra_client_order.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bra_invoice')
    ### end Alembic commands ###
