"""add models for searchad

Revision ID: 9c4785163d3
Revises: 415be74d0a74
Create Date: 2015-07-31 15:09:27.586472

"""

# revision identifiers, used by Alembic.
revision = '9c4785163d3'
down_revision = '415be74d0a74'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searchAd_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchAd_bra_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchAd_agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('tax_num', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('phone_num', sa.String(length=100), nullable=True),
    sa.Column('bank', sa.String(length=100), nullable=True),
    sa.Column('bank_num', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['searchAd_bra_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchAd_medium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('abbreviation', sa.String(length=100), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('tax_num', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('phone_num', sa.String(length=100), nullable=True),
    sa.Column('bank', sa.String(length=100), nullable=True),
    sa.Column('bank_num', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchAd_bra_agent_rebate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('inad_rebate', sa.Float(), nullable=True),
    sa.Column('douban_rebate', sa.Float(), nullable=True),
    sa.Column('year', sa.Date(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['searchAd_agent.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'year', name='_searchAd_agent_rebate_year')
    )
    op.create_table('searchAd_bra_medium_rebate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medium_id', sa.Integer(), nullable=True),
    sa.Column('rebate', sa.Float(), nullable=True),
    sa.Column('year', sa.Date(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['medium_id'], ['searchAd_medium.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medium_id', 'year', name='_searchAd_medium_rebate_year')
    )
    op.create_table('searchAd_bra_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign', sa.String(length=100), nullable=True),
    sa.Column('medium_id', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.Integer(), nullable=True),
    sa.Column('medium_contract', sa.String(length=100), nullable=True),
    sa.Column('medium_money', sa.Integer(), nullable=True),
    sa.Column('medium_money2', sa.Integer(), nullable=True),
    sa.Column('sale_money', sa.Integer(), nullable=True),
    sa.Column('medium_CPM', sa.Integer(), nullable=True),
    sa.Column('sale_CPM', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('medium_start', sa.Date(), nullable=True),
    sa.Column('medium_end', sa.Date(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['medium_id'], ['searchAd_medium.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchAd_bra_client_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('campaign', sa.String(length=100), nullable=True),
    sa.Column('contract', sa.String(length=100), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.Column('contract_type', sa.Integer(), nullable=True),
    sa.Column('client_start', sa.Date(), nullable=True),
    sa.Column('client_end', sa.Date(), nullable=True),
    sa.Column('reminde_date', sa.Date(), nullable=True),
    sa.Column('resource_type', sa.Integer(), nullable=True),
    sa.Column('sale_type', sa.Integer(), nullable=True),
    sa.Column('contract_status', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('back_money_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['searchAd_agent.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['searchAd_client.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchAd_bra_client_order_reject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.Column('reject_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], ['searchAd_bra_client_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id', 'reject_time', name='_searchAd_client_order_reject_time')
    )
    op.create_table('searchAd_order_users_operater',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['searchAd_bra_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('searchAd_ad_position_unit',
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['ad_position.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['ad_unit.id'], )
    )
    op.create_table('searchAd_client_order_medium_orders',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], ['searchAd_bra_client_order.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['searchAd_bra_order.id'], )
    )
    op.create_table('searchAd_bra_client_order_executive_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('month_day', sa.DateTime(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], ['searchAd_bra_client_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id', 'month_day', name='_searchAd_client_order_month_day')
    )
    op.create_table('searchAd_bra_medium_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.Column('medium_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('bank_id', sa.String(length=100), nullable=True),
    sa.Column('bank', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('pay_money', sa.Float(), nullable=True),
    sa.Column('invoice_type', sa.Integer(), nullable=True),
    sa.Column('invoice_status', sa.Integer(), nullable=True),
    sa.Column('invoice_num', sa.String(length=200), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.Column('pay_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('bool_pay', sa.Boolean(), nullable=True),
    sa.Column('bool_invoice', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], ['searchAd_bra_client_order.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['medium_id'], ['searchAd_medium.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchAd_client_order_direct_sales',
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], ['searchAd_bra_client_order.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['user.id'], )
    )
    op.create_table('searchAd_bra_medium_rebate_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.Column('medium_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('bank_id', sa.String(length=50), nullable=True),
    sa.Column('bank', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('invoice_type', sa.Integer(), nullable=True),
    sa.Column('invoice_status', sa.Integer(), nullable=True),
    sa.Column('invoice_num', sa.String(length=200), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('back_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], ['searchAd_bra_client_order.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['medium_id'], ['searchAd_medium.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchAd_client_order_agent_sales',
    sa.Column('agent_sale_id', sa.Integer(), nullable=True),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_sale_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['client_order_id'], ['searchAd_bra_client_order.id'], )
    )
    op.create_table('searchAd_bra_client_order_back_money',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('back_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], ['searchAd_bra_client_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchAd_order_users_designerer',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['searchAd_bra_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('searchAd_bra_medium_order_executive_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('medium_money', sa.Float(), nullable=True),
    sa.Column('medium_money2', sa.Float(), nullable=True),
    sa.Column('sale_money', sa.Float(), nullable=True),
    sa.Column('month_day', sa.DateTime(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], ['searchAd_bra_client_order.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['searchAd_bra_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id', 'order_id', 'month_day', name='_searchAd_medium_order_month_day')
    )
    op.create_table('searchAd_order_users_planer',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['searchAd_bra_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('searchAd_bra_client_order_back_invoice_rebate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.Column('num', sa.String(length=100), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('back_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], ['searchAd_bra_client_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchAd_bra_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('bank_id', sa.String(length=50), nullable=True),
    sa.Column('bank', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('invoice_type', sa.Integer(), nullable=True),
    sa.Column('invoice_status', sa.Integer(), nullable=True),
    sa.Column('invoice_num', sa.String(length=200), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('back_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], ['searchAd_bra_client_order.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchAd_bra_agent_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('bank_id', sa.String(length=100), nullable=True),
    sa.Column('bank', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('pay_money', sa.Float(), nullable=True),
    sa.Column('invoice_type', sa.Integer(), nullable=True),
    sa.Column('invoice_status', sa.Integer(), nullable=True),
    sa.Column('invoice_num', sa.String(length=200), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.Column('pay_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('bool_pay', sa.Boolean(), nullable=True),
    sa.Column('bool_invoice', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['searchAd_agent.id'], ),
    sa.ForeignKeyConstraint(['client_order_id'], ['searchAd_bra_client_order.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchAd_bra_agent_invoice_pay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_invoice_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.Column('pay_status', sa.Integer(), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('pay_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_invoice_id'], ['searchAd_bra_agent_invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchAd_bra_medium_invoice_pay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medium_invoice_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.Column('pay_status', sa.Integer(), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('pay_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medium_invoice_id'], ['searchAd_bra_medium_invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('client_report_month_day_index', table_name='bra_client_order_executive_report')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('client_report_month_day_index', 'bra_client_order_executive_report', ['month_day'], unique=False)
    op.drop_table('searchAd_bra_medium_invoice_pay')
    op.drop_table('searchAd_bra_agent_invoice_pay')
    op.drop_table('searchAd_bra_agent_invoice')
    op.drop_table('searchAd_bra_invoice')
    op.drop_table('searchAd_bra_client_order_back_invoice_rebate')
    op.drop_table('searchAd_order_users_planer')
    op.drop_table('searchAd_bra_medium_order_executive_report')
    op.drop_table('searchAd_order_users_designerer')
    op.drop_table('searchAd_bra_client_order_back_money')
    op.drop_table('searchAd_client_order_agent_sales')
    op.drop_table('searchAd_bra_medium_rebate_invoice')
    op.drop_table('searchAd_client_order_direct_sales')
    op.drop_table('searchAd_bra_medium_invoice')
    op.drop_table('searchAd_bra_client_order_executive_report')
    op.drop_table('searchAd_client_order_medium_orders')
    op.drop_table('searchAd_ad_position_unit')
    op.drop_table('searchAd_order_users_operater')
    op.drop_table('searchAd_bra_client_order_reject')
    op.drop_table('searchAd_bra_client_order')
    op.drop_table('searchAd_bra_order')
    op.drop_table('searchAd_bra_medium_rebate')
    op.drop_table('searchAd_bra_agent_rebate')
    op.drop_table('searchAd_medium')
    op.drop_table('searchAd_agent')
    op.drop_table('searchAd_bra_group')
    op.drop_table('searchAd_client')
    ### end Alembic commands ###
