"""add self_medium_rebate

Revision ID: a0254c52e31
Revises: 58cb643766b7
Create Date: 2016-05-26 12:34:26.322478

"""

# revision identifiers, used by Alembic.
revision = 'a0254c52e31'
down_revision = '58cb643766b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_order', sa.Column('self_medium_rebate', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_order', 'self_medium_rebate')
    ### end Alembic commands ###
