"""alter column start end date to datetime

Revision ID: aa785597071
Revises: 194af7c724af
Create Date: 2015-04-28 11:14:18.102437

"""

# revision identifiers, used by Alembic.
revision = 'aa785597071'
down_revision = '194af7c724af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_leave', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('user_leave', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.drop_column('user_leave', 'start')
    op.drop_column('user_leave', 'end')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_leave', sa.Column('end', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('user_leave', sa.Column('start', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('user_leave', 'start_time')
    op.drop_column('user_leave', 'end_time')
    ### end Alembic commands ###
