"""add colum tax tax_id in medium

Revision ID: aef2703eea9
Revises: 2edc21c21560
Create Date: 2015-03-31 12:02:27.886176

"""

# revision identifiers, used by Alembic.
revision = 'aef2703eea9'
down_revision = '2edc21c21560'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medium', sa.Column('address', sa.String(length=100), nullable=True))
    op.add_column('medium', sa.Column('bank', sa.String(length=100), nullable=True))
    op.add_column('medium', sa.Column('bank_num', sa.String(length=100), nullable=True))
    op.add_column('medium', sa.Column('phone_num', sa.String(length=100), nullable=True))
    op.add_column('medium', sa.Column('tax_num', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medium', 'tax_num')
    op.drop_column('medium', 'phone_num')
    op.drop_column('medium', 'bank_num')
    op.drop_column('medium', 'bank')
    op.drop_column('medium', 'address')
    ### end Alembic commands ###
