"""add client order

Revision ID: cac45bb56be
Revises: 4823715e2dc4
Create Date: 2014-12-15 12:40:42.988161

"""

# revision identifiers, used by Alembic.
revision = 'cac45bb56be'
down_revision = '4823715e2dc4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bra_client_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('campaign', sa.String(length=100), nullable=True),
    sa.Column('contract', sa.String(length=100), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.Column('contract_type', sa.Integer(), nullable=True),
    sa.Column('client_start', sa.Date(), nullable=True),
    sa.Column('client_end', sa.Date(), nullable=True),
    sa.Column('reminde_date', sa.Date(), nullable=True),
    sa.Column('resource_type', sa.Integer(), nullable=True),
    sa.Column('contract_status', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_order_users_operater',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], ['bra_client_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('client_order_medium_orders',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], ['bra_client_order.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['bra_order.id'], )
    )
    op.create_table('client_order_direct_sales',
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], ['bra_client_order.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['user.id'], )
    )
    op.create_table('client_order_users_planer',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], ['bra_client_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('client_order_users_designerer',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_order_id'], ['bra_client_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('client_order_agent_sales',
    sa.Column('agent_sale_id', sa.Integer(), nullable=True),
    sa.Column('client_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_sale_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['client_order_id'], ['bra_client_order.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_order_agent_sales')
    op.drop_table('client_order_users_designerer')
    op.drop_table('client_order_users_planer')
    op.drop_table('client_order_direct_sales')
    op.drop_table('client_order_medium_orders')
    op.drop_table('client_order_users_operater')
    op.drop_table('bra_client_order')
    ### end Alembic commands ###
