"""add table searchAd_bra_bill_invoice

Revision ID: d5ab4da2fcb
Revises: 1ca90d044092
Create Date: 2016-09-06 17:26:09.256511

"""

# revision identifiers, used by Alembic.
revision = 'd5ab4da2fcb'
down_revision = '1ca90d044092'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
