"""add colum is_win in case

Revision ID: e48d7e4a8ff
Revises: 2adc8cc5104c
Create Date: 2015-10-21 14:57:02.832860

"""

# revision identifiers, used by Alembic.
revision = 'e48d7e4a8ff'
down_revision = '2adc8cc5104c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_case', sa.Column('is_win', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_case', 'is_win')
    ### end Alembic commands ###
