"""update outsource column create_time

Revision ID: f1febdac97
Revises: 27a73dbf3b0b
Create Date: 2015-04-21 11:55:08.992068

"""

# revision identifiers, used by Alembic.
revision = 'f1febdac97'
down_revision = '27a73dbf3b0b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('douban_out_source', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('merger_out_source', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('out_source', sa.Column('create_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('out_source', 'create_time')
    op.drop_column('merger_out_source', 'create_time')
    op.drop_column('douban_out_source', 'create_time')
    ### end Alembic commands ###
