"""add column status in IntertionOrder

Revision ID: f4407b14bef
Revises: 394e07b25411
Create Date: 2016-04-25 10:37:14.380185

"""

# revision identifiers, used by Alembic.
revision = 'f4407b14bef'
down_revision = '394e07b25411'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bra_intention_order', sa.Column('ex_money', sa.Text(), nullable=True))
    op.add_column('bra_intention_order', sa.Column('status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bra_intention_order', 'status')
    op.drop_column('bra_intention_order', 'ex_money')
    ### end Alembic commands ###
